fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  git_pull
end

platform :android do
  # Android Lanes
  lane :betaandro do
  commit = last_git_commit
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(task: 'clean', project_dir: './')
  gradle(task: 'assemble', build_type: 'Release', project_dir: './')
  hockey(
  api_token: "bb564fe7c7bf42cb8dba7ec7ad7fd7fb",
  create_update: true,
  public_identifier: "dcc2083fdec64ba6908ab63ebf7044cf",
  bundle_short_version: "1.0.0",
  bundle_version: "1",
  notes: commit[:message]
  )

  end
end
